language: node_js
dist: trusty
sudo: required
node_js: stable
addons:
  apt:
    packages:
      - docker-ce
install:
  - npm install bower browserify -g
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
  - npm -s test
