language: node_js
dist: bionic
sudo: required
node_js: stable
env:
  - NODE_ENV=production
addons:
  apt:
    packages:
      - build-essential
      - docker-ce
cache:
  directories:
    - node_modules
install:
  - npm run -s setup
script:
  - npm run -s build
  - npm run -s test
  - sh docker_deploy.sh
after_script:
  - docker logout
