language: node_js
dist: trusty
sudo: required
node_js: stable
addons:
  apt:
    packages:
      - docker-ce
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install bower browserify -g
  - npm install
  - bower install
script:
  - npm run -s build
  - npm run -s test
  - sh docker_deploy.sh
after_script:
  - docker logout
